- hosts: localhost
  become: true

  vars:
    app_repo: "https://github.com/pranitpotsure/project-app.git"
    frontend_dir: "/opt/student-frontend"

  tasks:

    - name: Install required packages
      yum:
        name:
          - nginx
          - git
          - nodejs
        state: present

    - name: Ensure frontend directory is clean
      file:
        path: "{{ frontend_dir }}"
        state: absent

    - name: Clone application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ frontend_dir }}"
        version: main
        force: yes

    - name: Fix ownership to ec2-user
      file:
        path: "{{ frontend_dir }}"
        owner: ec2-user
        group: ec2-user
        recurse: yes

    - name: Install frontend dependencies
      become_user: ec2-user
      command: npm install
      args:
        chdir: "{{ frontend_dir }}/ems-frontend"

    - name: Build React frontend
      become_user: ec2-user
      command: npm run build
      args:
        chdir: "{{ frontend_dir }}/ems-frontend"

    - name: Remove old nginx files
      file:
        path: /usr/share/nginx/html
        state: absent

    - name: Recreate nginx root directory
      file:
        path: /usr/share/nginx/html
        state: directory
        owner: nginx
        group: nginx

    - name: Deploy frontend build to Nginx
      copy:
        src: "{{ frontend_dir }}/ems-frontend/dist/"
        dest: /usr/share/nginx/html/
        remote_src: yes

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/conf.d/student-app.conf
        content: |
          server {
              listen 80;
              server_name _;

              root /usr/share/nginx/html;
              index index.html;

              location / {
                  try_files $uri /index.html;
              }

              location /api/ {
                  proxy_pass http://{{ internal_alb_dns }}:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              }
          }

    - name: Enable and restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
